export const ValueType = {
  NUMBER: "NUMBER",
  NUMBERS_1_12: "NUMBERS_1_12",
  NUMBERS_2_12: "NUMBERS_2_12",
  NUMBERS_3_12: "NUMBERS_3_12",
  NUMBERS_1_18: "NUMBERS_1_18",
  NUMBERS_19_36: "NUMBERS_19_36",
  EVEN: "EVEN",
  ODD: "ODD",
  RED: "RED",
  BLACK: "BLACK",
  DOUBLE_SPLIT: "DOUBLE_SPLIT",
  QUAD_SPLIT: "QUAD_SPLIT",
  TRIPLE_SPLIT: "TRIPLE_SPLIT",
  EMPTY: "EMPTY",
};

export const GameStages = {
  PLACE_BET: "PLACE_BET",
  NO_MORE_BETS: "NO_MORE_BETS",
  WINNERS: "WINNERS",
  NONE: "NONE",
};
